"""Cadivor Sprint 51 — launch marketing website.

This module owns only the signed-out public marketing experience. It does not
modify authenticated workspace routing, analysis state, or scrolling behavior.
"""
from __future__ import annotations

from html import escape
from textwrap import dedent

import streamlit as st


PRODUCT_LINKS = [
    ("product", "Product"),
    ("solutions", "Solutions"),
    ("pricing", "Pricing"),
    ("resources", "Resources"),
    ("company", "Company"),
]


def _html(markup: str) -> None:
    st.markdown(dedent(markup).strip(), unsafe_allow_html=True)


def _marketing_css() -> None:
    st.markdown(
        """
        <style>
        :root{
          --mk-navy:#07162f;--mk-navy-2:#0b2145;--mk-blue:#2563eb;--mk-blue-2:#1d4ed8;
          --mk-cyan:#60a5fa;--mk-ink:#0f172a;--mk-copy:#52647a;--mk-muted:#64748b;
          --mk-border:#dfe7f1;--mk-soft:#f5f8fc;--mk-green:#16a34a;--mk-amber:#d97706;
          --mk-red:#dc2626;--mk-shadow:0 28px 80px rgba(7,22,47,.12);
        }
        html,body,.stApp,[data-testid="stAppViewContainer"]{background:#fff!important;color:var(--mk-ink)!important;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif!important;scroll-behavior:smooth;}
        [data-testid="stHeader"],[data-testid="stToolbar"],[data-testid="stDecoration"],section[data-testid="stSidebar"],[data-testid="collapsedControl"]{display:none!important;}
        .block-container{width:100%!important;max-width:none!important;padding:0!important;margin:0!important;}
        .mk-shell{width:100%;overflow:hidden}.mk-wrap{width:min(1180px,calc(100% - 48px));margin:0 auto}.mk-wide{width:min(1280px,calc(100% - 48px));margin:0 auto}
        .mk-nav-wrap{position:relative;z-index:20;background:var(--mk-navy);border-bottom:1px solid rgba(255,255,255,.08)}
        .mk-nav{height:78px;display:flex;align-items:center;justify-content:space-between;gap:28px}.mk-brand{display:flex;align-items:center;gap:12px;color:#fff!important;text-decoration:none!important;font-size:25px;font-weight:950;letter-spacing:-.045em}.mk-logo{width:39px;height:39px;border-radius:12px;display:grid;place-items:center;background:linear-gradient(145deg,#3b82f6,#1d4ed8);box-shadow:0 12px 30px rgba(37,99,235,.38);font-weight:950;color:#fff!important}
        .mk-links{display:flex;align-items:center;gap:25px;font-size:14px;font-weight:800}.mk-links a{color:#cbd5e1!important;text-decoration:none!important}.mk-links a:hover,.mk-links a.active{color:#fff!important}.mk-nav-actions{display:flex;align-items:center;gap:11px}.mk-btn{display:inline-flex;align-items:center;justify-content:center;min-height:44px;padding:0 18px;border-radius:10px;text-decoration:none!important;font-size:14px;font-weight:900;white-space:nowrap}.mk-btn-primary{background:var(--mk-blue);border:1px solid var(--mk-blue);color:#fff!important;box-shadow:0 13px 28px rgba(37,99,235,.28)}.mk-btn-primary:hover{background:var(--mk-blue-2);color:#fff!important}.mk-btn-light{background:#fff;border:1px solid #d9e2ee;color:var(--mk-ink)!important;box-shadow:0 9px 24px rgba(15,23,42,.08)}.mk-btn-ghost{background:transparent;border:1px solid rgba(255,255,255,.3);color:#fff!important}
        .mk-hero{background:radial-gradient(circle at 75% 22%,rgba(37,99,235,.25),transparent 32%),linear-gradient(135deg,#07162f 0%,#0a1b39 56%,#102a57 100%);color:#fff;padding:92px 0 96px;position:relative}.mk-hero-grid{display:grid;grid-template-columns:minmax(0,.9fr) minmax(540px,1.1fr);gap:64px;align-items:center}.mk-eyebrow{display:inline-flex;align-items:center;gap:8px;padding:8px 13px;border-radius:999px;border:1px solid rgba(147,197,253,.28);background:rgba(37,99,235,.13);color:#bfdbfe!important;font-size:12px;font-weight:900;letter-spacing:.09em;text-transform:uppercase;margin-bottom:24px}.mk-eyebrow-dot{width:7px;height:7px;border-radius:99px;background:#60a5fa;box-shadow:0 0 0 5px rgba(96,165,250,.12)}
        .mk-hero h1{margin:0 0 23px;color:#fff!important;font-size:clamp(48px,5vw,75px);line-height:.99;letter-spacing:-.06em;font-weight:950}.mk-hero h1 span{color:#60a5fa!important}.mk-hero-copy{font-size:19px;line-height:1.68;color:#c7d2e3!important;max-width:610px;margin:0 0 31px}.mk-actions{display:flex;gap:13px;flex-wrap:wrap;margin-bottom:25px}.mk-proof{display:flex;gap:20px;flex-wrap:wrap;color:#aebed3!important;font-size:13px;font-weight:750}.mk-proof b{color:#86efac!important;margin-right:5px}
        .mk-product{background:#fff;border:1px solid rgba(255,255,255,.45);border-radius:15px;box-shadow:0 35px 95px rgba(0,0,0,.32);overflow:hidden;transform:perspective(1200px) rotateY(-1.5deg)}.mk-product-top{height:45px;background:#f8fafc;border-bottom:1px solid #e5eaf0;display:flex;align-items:center;justify-content:space-between;padding:0 15px}.mk-dots{display:flex;gap:6px}.mk-dots i{display:block;width:8px;height:8px;border-radius:99px;background:#cbd5e1}.mk-app{display:grid;grid-template-columns:118px 1fr;min-height:390px}.mk-side{background:#0b1831;padding:16px 9px}.mk-side-brand{color:#fff!important;font-size:12px;font-weight:950;margin:0 4px 18px}.mk-side-item{padding:8px 8px;border-radius:7px;color:#91a4bf!important;font-size:8px;font-weight:800;margin-bottom:4px}.mk-side-item.active{background:#1d4ed8;color:#fff!important}.mk-main{padding:18px;background:#f7f9fc}.mk-main-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:13px}.mk-main-head strong{color:#0f172a!important;font-size:15px}.mk-mini-button{font-size:7px;background:#2563eb;color:#fff!important;padding:6px 9px;border-radius:5px;font-weight:900}.mk-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.mk-kpi{background:#fff;border:1px solid #e2e8f0;border-radius:8px;padding:10px}.mk-kpi span{display:block;color:#64748b!important;font-size:6px;font-weight:850;text-transform:uppercase}.mk-kpi strong{display:block;color:#0f172a!important;font-size:17px;margin-top:5px}.mk-chart-grid{display:grid;grid-template-columns:1.25fr .75fr;gap:9px;margin-top:9px}.mk-panel{background:#fff;border:1px solid #e2e8f0;border-radius:8px;padding:10px;min-height:115px}.mk-panel-title{color:#0f172a!important;font-size:8px;font-weight:900;margin-bottom:8px}.mk-bars{height:69px;display:flex;gap:7px;align-items:flex-end;padding:0 7px;border-bottom:1px solid #e7edf4}.mk-bars i{display:block;flex:1;background:#3b82f6;border-radius:3px 3px 0 0}.mk-donut{width:70px;height:70px;border-radius:50%;margin:7px auto;background:conic-gradient(#2563eb 0 62%,#f59e0b 62% 82%,#ef4444 82% 100%);position:relative}.mk-donut:after{content:"";position:absolute;inset:15px;border-radius:50%;background:#fff}.mk-table{margin-top:9px;background:#fff;border:1px solid #e2e8f0;border-radius:8px;overflow:hidden}.mk-row{display:grid;grid-template-columns:1.5fr .8fr .65fr .65fr;gap:5px;padding:7px 9px;border-bottom:1px solid #eef2f6;font-size:6px;color:#475569!important}.mk-row.head{background:#f8fafc;font-weight:900;color:#64748b!important;text-transform:uppercase}.mk-row:last-child{border-bottom:0}.mk-risk{font-weight:900}.mk-risk.high{color:#dc2626!important}.mk-risk.medium{color:#d97706!important}.mk-risk.low{color:#16a34a!important}
        .mk-trust{background:#fff;border-bottom:1px solid #edf1f6;padding:25px 0}.mk-trust-inner{display:flex;align-items:center;justify-content:center;gap:44px;flex-wrap:wrap;color:#6b7b90!important;font-size:13px;font-weight:850}.mk-trust-label{color:#94a3b8!important;font-size:11px;text-transform:uppercase;letter-spacing:.13em}.mk-logo-text{font-size:17px;color:#586b83!important;font-weight:950}
        .mk-section{padding:88px 0}.mk-section.soft{background:var(--mk-soft)}.mk-section.dark{background:var(--mk-navy);color:#fff}.mk-heading{text-align:center;max-width:820px;margin:0 auto 45px}.mk-kicker{color:var(--mk-blue)!important;font-weight:950;font-size:12px;text-transform:uppercase;letter-spacing:.12em;margin-bottom:12px}.mk-heading h2{color:var(--mk-ink)!important;font-size:clamp(34px,4vw,50px);line-height:1.06;letter-spacing:-.05em;margin:0 0 17px;font-weight:950}.mk-heading p{color:var(--mk-copy)!important;font-size:17px;line-height:1.7;margin:0}.dark .mk-heading h2{color:#fff!important}.dark .mk-heading p{color:#b9c6d8!important}
        .mk-card-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.mk-card{background:#fff;border:1px solid var(--mk-border);border-radius:16px;padding:27px;box-shadow:0 14px 40px rgba(15,23,42,.06)}.mk-icon{width:43px;height:43px;border-radius:12px;background:#eaf2ff;color:#2563eb!important;display:grid;place-items:center;font-weight:950;font-size:18px;margin-bottom:18px}.mk-card h3{font-size:18px;color:var(--mk-ink)!important;margin:0 0 9px;font-weight:950;letter-spacing:-.025em}.mk-card p{font-size:14px;line-height:1.65;color:var(--mk-copy)!important;margin:0}.mk-card a{display:inline-block;margin-top:15px;color:#2563eb!important;text-decoration:none!important;font-size:13px;font-weight:900}
        .mk-feature-split{display:grid;grid-template-columns:1fr 1fr;gap:65px;align-items:center}.mk-feature-copy h2{font-size:43px;line-height:1.08;letter-spacing:-.05em;color:var(--mk-ink)!important;margin:0 0 18px;font-weight:950}.mk-feature-copy>p{color:var(--mk-copy)!important;font-size:17px;line-height:1.7}.mk-check-list{display:grid;gap:14px;margin-top:25px}.mk-check{display:flex;gap:12px;align-items:flex-start}.mk-check b{width:23px;height:23px;flex:none;border-radius:99px;background:#dcfce7;color:#15803d!important;display:grid;place-items:center;font-size:12px}.mk-check span{color:#334155!important;font-size:14px;line-height:1.55;font-weight:700}.mk-surface{background:#fff;border:1px solid var(--mk-border);border-radius:18px;padding:22px;box-shadow:var(--mk-shadow)}.mk-cockpit{background:#0b1831;border-radius:13px;padding:20px;color:#fff}.mk-cockpit-title{font-size:13px;color:#fff!important;font-weight:950;margin-bottom:13px}.mk-cockpit-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.mk-cockpit-card{background:#13284c;border:1px solid rgba(255,255,255,.08);padding:12px;border-radius:8px}.mk-cockpit-card span{display:block;color:#9eb0c8!important;font-size:7px;text-transform:uppercase;font-weight:850}.mk-cockpit-card strong{display:block;color:#fff!important;font-size:18px;margin-top:5px}.mk-recommendation{margin-top:10px;background:#102f5d;border-left:3px solid #60a5fa;border-radius:7px;padding:13px;color:#dbeafe!important;font-size:10px;line-height:1.5}
        .mk-steps{display:grid;grid-template-columns:repeat(4,1fr);gap:18px}.mk-step{text-align:center;position:relative}.mk-step-num{width:49px;height:49px;margin:0 auto 17px;border-radius:50%;display:grid;place-items:center;background:#eaf2ff;color:#2563eb!important;font-size:16px;font-weight:950}.mk-step h3{font-size:17px;color:#0f172a!important;margin:0 0 8px}.mk-step p{font-size:13px;line-height:1.6;color:#64748b!important;margin:0}.mk-step:not(:last-child):after{content:"";position:absolute;top:24px;left:65%;width:70%;height:1px;background:#cfd9e6}
        .mk-testimonials{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.mk-quote{background:#fff;border:1px solid var(--mk-border);border-radius:16px;padding:26px;box-shadow:0 14px 38px rgba(15,23,42,.06)}.mk-quote p{font-size:15px;line-height:1.7;color:#334155!important;margin:0 0 21px}.mk-person{display:flex;align-items:center;gap:11px}.mk-avatar{width:38px;height:38px;border-radius:50%;display:grid;place-items:center;background:#dbeafe;color:#1d4ed8!important;font-weight:950}.mk-person strong{display:block;color:#0f172a!important;font-size:13px}.mk-person span{display:block;color:#64748b!important;font-size:11px;margin-top:2px}
        .mk-pricing{display:grid;grid-template-columns:repeat(4,1fr);gap:17px}.mk-price-card{background:#fff;border:1px solid var(--mk-border);border-radius:17px;padding:27px;position:relative}.mk-price-card.featured{border:2px solid #2563eb;box-shadow:0 22px 55px rgba(37,99,235,.13)}.mk-popular{position:absolute;top:-12px;right:17px;padding:5px 9px;border-radius:999px;background:#2563eb;color:#fff!important;font-size:9px;font-weight:950;text-transform:uppercase;letter-spacing:.08em}.mk-price-name{font-size:18px;color:#0f172a!important;font-weight:950}.mk-price{font-size:31px;color:#0f172a!important;font-weight:950;margin:12px 0 5px;letter-spacing:-.04em}.mk-price small{font-size:12px;color:#64748b!important}.mk-price-card>p{font-size:13px;line-height:1.55;color:#64748b!important;min-height:61px}.mk-price-card ul{list-style:none;margin:20px 0 23px;padding:0;display:grid;gap:10px}.mk-price-card li{font-size:12px;color:#334155!important;font-weight:750}.mk-price-card li:before{content:"✓";color:#16a34a;margin-right:7px;font-weight:950}.mk-price-card .mk-btn{width:100%;box-sizing:border-box}
        .mk-faq{display:grid;grid-template-columns:1fr 1fr;gap:14px}.mk-faq-item{background:#fff;border:1px solid var(--mk-border);border-radius:13px;padding:21px}.mk-faq-item strong{display:block;color:#0f172a!important;font-size:14px;margin-bottom:8px}.mk-faq-item p{color:#64748b!important;font-size:13px;line-height:1.6;margin:0}
        .mk-page-hero{background:radial-gradient(circle at 75% 20%,rgba(37,99,235,.23),transparent 34%),var(--mk-navy);padding:82px 0 76px;color:#fff}.mk-page-hero h1{font-size:clamp(43px,5vw,66px);line-height:1;letter-spacing:-.055em;color:#fff!important;margin:0 0 20px;font-weight:950;max-width:850px}.mk-page-hero p{font-size:18px;line-height:1.7;color:#c2cfdf!important;max-width:760px;margin:0}.mk-page-hero .mk-actions{margin-top:27px;margin-bottom:0}.mk-subnav{background:#fff;border-bottom:1px solid var(--mk-border);padding:15px 0}.mk-subnav-inner{display:flex;gap:22px;overflow:auto}.mk-subnav a{font-size:13px;color:#52647a!important;text-decoration:none!important;font-weight:850;white-space:nowrap}.mk-subnav a:hover{color:#2563eb!important}
        .mk-industry-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:20px}.mk-industry{background:#fff;border:1px solid var(--mk-border);border-radius:16px;padding:28px}.mk-industry h3{color:#0f172a!important;margin:0 0 9px;font-size:19px}.mk-industry p{color:#64748b!important;line-height:1.65;font-size:14px}.mk-industry ul{padding-left:18px;color:#475569}.mk-industry li{margin:7px 0;font-size:13px}.mk-industry a{color:#2563eb!important;text-decoration:none!important;font-weight:900;font-size:13px}
        .mk-resource-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.mk-resource{background:#fff;border:1px solid var(--mk-border);border-radius:16px;padding:25px}.mk-resource-type{color:#2563eb!important;text-transform:uppercase;letter-spacing:.1em;font-size:10px;font-weight:950}.mk-resource h3{color:#0f172a!important;font-size:18px;margin:11px 0 8px}.mk-resource p{color:#64748b!important;font-size:13px;line-height:1.65}.mk-resource a{color:#2563eb!important;font-weight:900;text-decoration:none!important;font-size:13px}
        .mk-compare{width:100%;border-collapse:separate;border-spacing:0;background:#fff;border:1px solid var(--mk-border);border-radius:16px;overflow:hidden}.mk-compare th,.mk-compare td{padding:15px 17px;border-bottom:1px solid #edf1f6;text-align:left;font-size:12px}.mk-compare th{background:#f8fafc;color:#475569!important;text-transform:uppercase;font-size:10px;letter-spacing:.08em}.mk-compare td{color:#334155!important}.mk-compare tr:last-child td{border-bottom:0}.mk-yes{color:#16a34a!important;font-weight:950}.mk-partial{color:#d97706!important;font-weight:950}
        .mk-cta{background:linear-gradient(135deg,#0b2145,#12376d);border:1px solid rgba(255,255,255,.12);border-radius:21px;padding:48px 54px;display:flex;align-items:center;justify-content:space-between;gap:35px;box-shadow:0 30px 80px rgba(7,22,47,.22)}.mk-cta h2{color:#fff!important;margin:0 0 9px;font-size:32px;letter-spacing:-.04em}.mk-cta p{color:#b9c7da!important;margin:0;font-size:15px}.mk-footer{background:#061329;color:#fff;padding:62px 0 28px}.mk-footer-grid{display:grid;grid-template-columns:1.5fr repeat(4,1fr);gap:42px}.mk-footer-brand p{color:#92a4bd!important;font-size:13px;line-height:1.65;max-width:330px}.mk-footer-col strong{color:#fff!important;font-size:12px;text-transform:uppercase;letter-spacing:.09em}.mk-footer-col a{display:block;color:#9fb0c7!important;text-decoration:none!important;font-size:12px;margin-top:12px}.mk-footer-col a:hover{color:#fff!important}.mk-footer-bottom{display:flex;justify-content:space-between;gap:20px;margin-top:45px;padding-top:20px;border-top:1px solid rgba(255,255,255,.08);color:#778aa5!important;font-size:11px}
        @media(max-width:1050px){.mk-links{display:none}.mk-hero-grid,.mk-feature-split{grid-template-columns:1fr}.mk-product{transform:none;max-width:820px}.mk-card-grid,.mk-pricing,.mk-resource-grid{grid-template-columns:repeat(2,1fr)}.mk-steps{grid-template-columns:repeat(2,1fr)}.mk-step:after{display:none}.mk-footer-grid{grid-template-columns:1.5fr repeat(2,1fr)}}
        @media(max-width:680px){.mk-wrap,.mk-wide{width:min(100% - 28px,1180px)}.mk-nav{height:auto;padding:14px 0;align-items:flex-start}.mk-nav-actions .mk-btn-ghost{display:none}.mk-brand{font-size:21px}.mk-hero{padding:64px 0}.mk-hero h1{font-size:47px}.mk-hero-grid{gap:44px}.mk-app{grid-template-columns:1fr}.mk-side{display:none}.mk-kpis{grid-template-columns:repeat(2,1fr)}.mk-chart-grid{grid-template-columns:1fr}.mk-card-grid,.mk-pricing,.mk-testimonials,.mk-faq,.mk-industry-grid,.mk-resource-grid,.mk-steps{grid-template-columns:1fr}.mk-section{padding:68px 0}.mk-feature-copy h2{font-size:36px}.mk-cta{padding:34px 27px;align-items:flex-start;flex-direction:column}.mk-footer-grid{grid-template-columns:1fr 1fr}.mk-footer-brand{grid-column:1/-1}.mk-footer-bottom{flex-direction:column}.mk-trust-inner{gap:22px}.mk-logo-text{font-size:14px}}
        </style>
        """,
        unsafe_allow_html=True,
    )


def _nav(active: str = "home") -> None:
    links = "".join(
        f'<a class="{"active" if key == active else ""}" href="?public={key}" target="_self">{label}</a>'
        for key, label in PRODUCT_LINKS
    )
    _html(f"""
    <div class="mk-nav-wrap"><div class="mk-wrap mk-nav">
      <a class="mk-brand" href="?public=home" target="_self"><span class="mk-logo">C</span>Cadivor</a>
      <div class="mk-links">{links}</div>
      <div class="mk-nav-actions"><a class="mk-btn mk-btn-ghost" href="?auth=login" target="_self">Sign In</a><a class="mk-btn mk-btn-primary" href="?auth=signup" target="_self">Start Free Trial</a></div>
    </div></div>
    """)


def _footer() -> None:
    _html("""
    <footer class="mk-footer"><div class="mk-wrap">
      <div class="mk-footer-grid">
        <div class="mk-footer-brand"><a class="mk-brand" href="?public=home" target="_self"><span class="mk-logo">C</span>Cadivor</a><p>Engineering intelligence that helps hardware teams understand BOM risk, evaluate alternatives, and make better decisions before production.</p></div>
        <div class="mk-footer-col"><strong>Product</strong><a href="?public=product">Overview</a><a href="?public=product#engineering-intelligence">Engineering Intelligence</a><a href="?public=product#copilot">Ask Cadivor</a><a href="?public=pricing">Pricing</a></div>
        <div class="mk-footer-col"><strong>Solutions</strong><a href="?public=solutions#robotics">Robotics</a><a href="?public=solutions#medical">Medical Devices</a><a href="?public=solutions#industrial">Industrial Automation</a><a href="?public=solutions#startups">Hardware Startups</a></div>
        <div class="mk-footer-col"><strong>Resources</strong><a href="?public=resources">Getting Started</a><a href="?public=resources">Demo BOMs</a><a href="?public=resources">Engineering Guides</a><a href="?public=resources">FAQ</a></div>
        <div class="mk-footer-col"><strong>Company</strong><a href="?public=company">About</a><a href="?public=security">Security</a><a href="?public=contact">Contact</a><a href="?public=privacy">Privacy</a><a href="?public=terms">Terms</a></div>
      </div>
      <div class="mk-footer-bottom"><span>© 2026 Cadivor. All rights reserved.</span><span>Engineering decision support—not a replacement for professional validation.</span></div>
    </div></footer>
    """)


def _cta(title: str = "Make your next BOM review faster and more decisive.", copy: str = "Start with a 14-day full-access trial. No credit card required.") -> None:
    _html(f"""
    <section class="mk-section"><div class="mk-wrap"><div class="mk-cta">
      <div><h2>{escape(title)}</h2><p>{escape(copy)}</p></div>
      <div class="mk-actions" style="margin:0"><a class="mk-btn mk-btn-primary" href="?auth=signup" target="_self">Start Free Trial</a><a class="mk-btn mk-btn-light" href="?public=contact" target="_self">Book a Demo</a></div>
    </div></div></section>
    """)


def _dashboard_mockup() -> str:
    return """
    <div class="mk-product">
      <div class="mk-product-top"><div class="mk-dots"><i></i><i></i><i></i></div><span style="font-size:8px;color:#64748b;font-weight:850">Cadivor Engineering Intelligence</span></div>
      <div class="mk-app"><div class="mk-side"><div class="mk-side-brand">CADIVOR</div><div class="mk-side-item active">⌂ Dashboard</div><div class="mk-side-item">▦ BOM Analyzer</div><div class="mk-side-item">✦ Engineering Intelligence</div><div class="mk-side-item">◇ Alternative Finder</div><div class="mk-side-item">◉ Monitoring</div><div class="mk-side-item">▤ Reports</div></div>
      <div class="mk-main"><div class="mk-main-head"><strong>Engineering Dashboard</strong><span class="mk-mini-button">+ New Analysis</span></div>
      <div class="mk-kpis"><div class="mk-kpi"><span>Portfolio Health</span><strong>82</strong></div><div class="mk-kpi"><span>High Risk</span><strong>18</strong></div><div class="mk-kpi"><span>Alternatives</span><strong>47</strong></div><div class="mk-kpi"><span>Monitored</span><strong>1,248</strong></div></div>
      <div class="mk-chart-grid"><div class="mk-panel"><div class="mk-panel-title">Portfolio Risk Trend</div><div class="mk-bars"><i style="height:38%"></i><i style="height:48%"></i><i style="height:64%"></i><i style="height:52%"></i><i style="height:71%"></i><i style="height:59%"></i><i style="height:83%"></i><i style="height:68%"></i></div></div><div class="mk-panel"><div class="mk-panel-title">Risk Distribution</div><div class="mk-donut"></div></div></div>
      <div class="mk-table"><div class="mk-row head"><div>Analysis</div><div>Components</div><div>Health</div><div>Decision</div></div><div class="mk-row"><div>Robot Controller Rev C</div><div>418</div><div>84</div><div class="mk-risk medium">Review</div></div><div class="mk-row"><div>Medical Sensor Board</div><div>236</div><div>91</div><div class="mk-risk low">Ready</div></div><div class="mk-row"><div>Industrial I/O Module</div><div>511</div><div>68</div><div class="mk-risk high">Hold</div></div></div>
      </div></div>
    </div>
    """


def _home() -> None:
    _nav("home")
    _html(f"""
    <main class="mk-shell">
      <section class="mk-hero"><div class="mk-wide mk-hero-grid">
        <div><div class="mk-eyebrow"><i class="mk-eyebrow-dot"></i>Engineering decision intelligence</div><h1>Make better engineering decisions. <span>Faster.</span></h1><p class="mk-hero-copy">Cadivor transforms BOM data into clear engineering intelligence—identifying lifecycle, sourcing, inventory, and production risks while recommending the actions your team should take next.</p><div class="mk-actions"><a class="mk-btn mk-btn-primary" href="?auth=signup" target="_self">Start Free Trial</a><a class="mk-btn mk-btn-light" href="?public=contact" target="_self">Book a Demo</a></div><div class="mk-proof"><span><b>✓</b>14-day full access</span><span><b>✓</b>No credit card required</span><span><b>✓</b>CSV and Excel BOMs</span></div></div>
        {_dashboard_mockup()}
      </div></section>
      <section class="mk-trust"><div class="mk-wrap mk-trust-inner"><span class="mk-trust-label">Connected supplier intelligence</span><span class="mk-logo-text">DigiKey</span><span class="mk-logo-text">Mouser</span><span class="mk-logo-text">Newark</span><span class="mk-logo-text">Supabase</span><span class="mk-logo-text">Stripe</span></div></section>
      <section class="mk-section"><div class="mk-wrap"><div class="mk-heading"><div class="mk-kicker">One connected platform</div><h2>From component data to confident decisions</h2><p>Cadivor connects BOM analysis, engineering reasoning, alternatives, monitoring, decisions, and reports in one workspace.</p></div><div class="mk-card-grid">
        <div class="mk-card"><div class="mk-icon">▦</div><h3>BOM Analyzer</h3><p>Upload CSV or Excel BOMs and identify lifecycle, supplier, inventory, and sourcing exposure across every component.</p><a href="?public=product" target="_self">Explore BOM analysis →</a></div>
        <div class="mk-card"><div class="mk-icon">✦</div><h3>Engineering Intelligence</h3><p>Move beyond raw risk flags with prioritized engineering conclusions, evidence, and release-oriented recommendations.</p><a href="?public=product#engineering-intelligence" target="_self">See engineering intelligence →</a></div>
        <div class="mk-card"><div class="mk-icon">C</div><h3>Ask Cadivor</h3><p>Ask follow-up questions about the active BOM and receive context-aware engineering guidance grounded in the analysis.</p><a href="?public=product#copilot" target="_self">Meet the copilot →</a></div>
        <div class="mk-card"><div class="mk-icon">◇</div><h3>Alternative Finder</h3><p>Shortlist replacement candidates with sourcing, lifecycle, and implementation context for structured qualification.</p><a href="?public=product#alternatives" target="_self">Review alternatives →</a></div>
        <div class="mk-card"><div class="mk-icon">◉</div><h3>Monitoring</h3><p>Track critical parts and surface meaningful changes before they become schedule, cost, or production problems.</p><a href="?public=product#monitoring" target="_self">Explore monitoring →</a></div>
        <div class="mk-card"><div class="mk-icon">▤</div><h3>Decision-Ready Reports</h3><p>Generate executive, lifecycle, sourcing, and engineering reports for cross-functional review and audit support.</p><a href="?public=product#reports" target="_self">See reports →</a></div>
      </div></div></section>
      <section class="mk-section soft" id="engineering-intelligence"><div class="mk-wrap mk-feature-split"><div class="mk-feature-copy"><div class="mk-kicker">Executive Decision Cockpit</div><h2>See what matters before production release.</h2><p>Cadivor translates a complex BOM into a concise decision view: release posture, highest-priority risks, confidence, evidence, and the next engineering actions.</p><div class="mk-check-list"><div class="mk-check"><b>✓</b><span>Prioritized risks instead of undifferentiated alerts</span></div><div class="mk-check"><b>✓</b><span>Release-oriented engineering recommendations</span></div><div class="mk-check"><b>✓</b><span>Evidence explaining why each conclusion matters</span></div><div class="mk-check"><b>✓</b><span>Persistent decision history for review continuity</span></div></div></div><div class="mk-surface"><div class="mk-cockpit"><div class="mk-cockpit-title">Executive Decision Cockpit</div><div class="mk-cockpit-grid"><div class="mk-cockpit-card"><span>Release posture</span><strong>HOLD</strong></div><div class="mk-cockpit-card"><span>Confidence</span><strong>87%</strong></div><div class="mk-cockpit-card"><span>Priority risks</span><strong>4</strong></div></div><div class="mk-recommendation"><b>Recommended decision:</b> Resolve the two single-source lifecycle risks before production release. Qualify the proposed alternate for the highest-exposure component first.</div></div></div></div></section>
      <section class="mk-section"><div class="mk-wrap"><div class="mk-heading"><div class="mk-kicker">How it works</div><h2>A faster path from BOM upload to engineering action</h2><p>Cadivor keeps the entire review connected, from first analysis through recommendation and decision.</p></div><div class="mk-steps"><div class="mk-step"><div class="mk-step-num">1</div><h3>Upload your BOM</h3><p>Import a CSV or Excel file with component part numbers and quantities.</p></div><div class="mk-step"><div class="mk-step-num">2</div><h3>Analyze exposure</h3><p>Check lifecycle, stock, suppliers, sourcing concentration, and alternatives.</p></div><div class="mk-step"><div class="mk-step-num">3</div><h3>Review intelligence</h3><p>Understand the release posture, priority risks, evidence, and recommendations.</p></div><div class="mk-step"><div class="mk-step-num">4</div><h3>Decide and monitor</h3><p>Record decisions, export reports, and monitor the parts that matter.</p></div></div></div></section>
      <section class="mk-section soft"><div class="mk-wrap"><div class="mk-heading"><div class="mk-kicker">Built for hardware teams</div><h2>Engineering confidence across the product lifecycle</h2><p>Cadivor supports early design review, production release, redesign, and ongoing component monitoring.</p></div><div class="mk-card-grid"><div class="mk-card"><div class="mk-icon">⚙</div><h3>Engineering</h3><p>Identify design and lifecycle risks earlier, compare alternatives, and document technical decisions.</p></div><div class="mk-card"><div class="mk-icon">$</div><h3>Procurement</h3><p>Understand stock, supplier concentration, sourcing constraints, and qualification priorities.</p></div><div class="mk-card"><div class="mk-icon">◆</div><h3>Leadership</h3><p>See portfolio health, release posture, priority actions, and decision-ready summaries.</p></div></div></div></section>
      <section class="mk-section"><div class="mk-wrap"><div class="mk-heading"><div class="mk-kicker">Beta program</div><h2>Built with engineering teams, not assumptions</h2><p>The launch program is designed around direct feedback from hardware teams reviewing real BOMs.</p></div><div class="mk-testimonials"><div class="mk-quote"><p>“The most useful part is not another risk score—it is seeing which issue should be addressed first and why.”</p><div class="mk-person"><div class="mk-avatar">E</div><div><strong>Engineering leader</strong><span>Beta feedback profile</span></div></div></div><div class="mk-quote"><p>“Cadivor brings lifecycle, sourcing, and engineering context together in a way that is easier to review with the wider team.”</p><div class="mk-person"><div class="mk-avatar">P</div><div><strong>Procurement professional</strong><span>Beta feedback profile</span></div></div></div><div class="mk-quote"><p>“The conversational review makes it easier to challenge a recommendation and understand what evidence would change it.”</p><div class="mk-person"><div class="mk-avatar">H</div><div><strong>Hardware engineer</strong><span>Beta feedback profile</span></div></div></div></div></div></section>
    </main>
    """)
    _cta()
    _footer()


def _page_hero(active: str, kicker: str, title: str, copy: str) -> None:
    _nav(active)
    _html(f"""
    <section class="mk-page-hero"><div class="mk-wrap"><div class="mk-eyebrow"><i class="mk-eyebrow-dot"></i>{escape(kicker)}</div><h1>{escape(title)}</h1><p>{escape(copy)}</p><div class="mk-actions"><a class="mk-btn mk-btn-primary" href="?auth=signup" target="_self">Start Free Trial</a><a class="mk-btn mk-btn-light" href="?public=contact" target="_self">Book a Demo</a></div></div></section>
    """)


def _product() -> None:
    _page_hero("product", "Cadivor platform", "Engineering intelligence from BOM to production.", "Analyze component exposure, understand what matters, qualify alternatives, record decisions, and monitor risk in one connected engineering workspace.")
    _html("""
    <div class="mk-subnav"><div class="mk-wrap mk-subnav-inner"><a href="#bom-analyzer">BOM Analyzer</a><a href="#engineering-intelligence">Engineering Intelligence</a><a href="#copilot">Ask Cadivor</a><a href="#alternatives">Alternative Finder</a><a href="#monitoring">Monitoring</a><a href="#reports">Reports</a></div></div>
    <section class="mk-section" id="bom-analyzer"><div class="mk-wrap mk-feature-split"><div class="mk-feature-copy"><div class="mk-kicker">BOM Analyzer</div><h2>Turn a parts list into an engineering review.</h2><p>Cadivor normalizes your BOM, gathers supplier intelligence, evaluates component health, and presents risk across the full design—not one distributor search at a time.</p><div class="mk-check-list"><div class="mk-check"><b>✓</b><span>CSV and Excel import with normalization and validation</span></div><div class="mk-check"><b>✓</b><span>Lifecycle, stock, supplier, and sourcing-risk analysis</span></div><div class="mk-check"><b>✓</b><span>Portfolio health score and prioritized component review</span></div></div></div><div class="mk-surface">""" + _dashboard_mockup() + """</div></div></section>
    <section class="mk-section soft" id="engineering-intelligence"><div class="mk-wrap"><div class="mk-heading"><div class="mk-kicker">Engineering Intelligence</div><h2>Move from alerts to engineering conclusions.</h2><p>Cadivor explains what the BOM evidence means for design release, procurement readiness, and production risk.</p></div><div class="mk-card-grid"><div class="mk-card"><div class="mk-icon">◆</div><h3>Executive Decision Cockpit</h3><p>Summarizes release posture, confidence, priority risks, evidence, and recommended next actions.</p></div><div class="mk-card"><div class="mk-icon">△</div><h3>Risk Prioritization</h3><p>Identifies which component or sourcing issue deserves attention first and why.</p></div><div class="mk-card"><div class="mk-icon">✓</div><h3>Decision Evidence</h3><p>Shows what supports a recommendation and what new evidence could change it.</p></div></div></div></section>
    <section class="mk-section" id="copilot"><div class="mk-wrap mk-feature-split"><div class="mk-surface"><div class="mk-cockpit"><div class="mk-cockpit-title">Ask Cadivor</div><div class="mk-recommendation" style="margin-top:0"><b>Question:</b> Is this BOM ready for production release?</div><div class="mk-recommendation"><b>Cadivor:</b> Not yet. Two components create unresolved single-source lifecycle exposure. Qualify the proposed alternate for U14 and verify the manufacturer lifecycle status for Q7 before release.</div><div class="mk-recommendation"><b>Follow-up:</b> What evidence would change this recommendation?</div></div></div><div class="mk-feature-copy"><div class="mk-kicker">Ask Cadivor</div><h2>Challenge the analysis in plain language.</h2><p>Ask context-aware questions about the active BOM, recommendation, supplier exposure, alternatives, production readiness, or the evidence needed to reach a different decision.</p><div class="mk-check-list"><div class="mk-check"><b>✓</b><span>Conversation stays connected to the active engineering review</span></div><div class="mk-check"><b>✓</b><span>Suggested questions accelerate common review workflows</span></div><div class="mk-check"><b>✓</b><span>Persistent review state supports continuity across navigation</span></div></div></div></div></section>
    <section class="mk-section soft" id="alternatives"><div class="mk-wrap"><div class="mk-heading"><div class="mk-kicker">Alternative Finder</div><h2>Shortlist replacements with engineering context.</h2><p>Compare replacement candidates using lifecycle, availability, supplier coverage, and implementation considerations—not part-number similarity alone.</p></div><div class="mk-card-grid"><div class="mk-card"><div class="mk-icon">1</div><h3>Rank candidates</h3><p>Surface the strongest replacement candidates based on the available component and sourcing evidence.</p></div><div class="mk-card"><div class="mk-icon">2</div><h3>Compare evidence</h3><p>Review lifecycle status, supplier coverage, inventory, and compatibility considerations side by side.</p></div><div class="mk-card"><div class="mk-icon">3</div><h3>Record the decision</h3><p>Approve, reject, or save a candidate with rationale and decision history.</p></div></div></div></section>
    <section class="mk-section" id="monitoring"><div class="mk-wrap mk-feature-split"><div class="mk-feature-copy"><div class="mk-kicker">Monitoring</div><h2>Keep critical components under review.</h2><p>Track the parts that matter after the initial BOM analysis. Cadivor helps teams maintain visibility into lifecycle, stock, and sourcing changes over time.</p><div class="mk-check-list"><div class="mk-check"><b>✓</b><span>Monitor priority components and saved analyses</span></div><div class="mk-check"><b>✓</b><span>Surface meaningful changes for engineering attention</span></div><div class="mk-check"><b>✓</b><span>Connect monitoring findings back to the decision workflow</span></div></div></div><div class="mk-surface"><div class="mk-card" style="box-shadow:none"><div class="mk-icon">◉</div><h3>Monitoring Center</h3><p>1,248 components monitored across active programs.</p><div class="mk-check-list"><div class="mk-check"><b>!</b><span>3 lifecycle changes need review</span></div><div class="mk-check"><b>!</b><span>7 inventory changes affect priority parts</span></div><div class="mk-check"><b>✓</b><span>Portfolio monitoring completed successfully</span></div></div></div></div></div></section>
    <section class="mk-section soft" id="reports"><div class="mk-wrap"><div class="mk-heading"><div class="mk-kicker">Reports and decisions</div><h2>Communicate engineering risk clearly.</h2><p>Export reports designed for engineers, sourcing teams, managers, and formal review workflows.</p></div><div class="mk-card-grid"><div class="mk-card"><div class="mk-icon">▤</div><h3>Executive BOM Summary</h3><p>A concise overview of BOM health, release posture, priority risks, and actions.</p></div><div class="mk-card"><div class="mk-icon">⌁</div><h3>Lifecycle Exposure Report</h3><p>Detailed lifecycle findings and component-level evidence for redesign planning.</p></div><div class="mk-card"><div class="mk-icon">◆</div><h3>Engineering Decision Record</h3><p>Structured decisions with rationale, status, confidence, and audit-friendly history.</p></div></div></div></section>
    """)
    _cta("Bring every BOM review into one connected workspace.", "Start with full platform access for 14 days.")
    _footer()


def _solutions() -> None:
    _page_hero("solutions", "Industry solutions", "Engineering intelligence for teams that build physical products.", "Cadivor helps hardware organizations identify component exposure earlier, improve cross-functional reviews, and make more defensible release decisions.")
    _html("""
    <section class="mk-section soft"><div class="mk-wrap"><div class="mk-industry-grid">
      <article class="mk-industry" id="robotics"><div class="mk-kicker">Robotics</div><h3>Protect long-lived robotic platforms from component disruption.</h3><p>Review controller, sensing, communications, and power-system BOMs for lifecycle and sourcing exposure before a fielded platform depends on fragile components.</p><ul><li>Prioritize single-source controller and sensor risks</li><li>Qualify alternates before production ramps</li><li>Monitor critical electronics across revisions</li></ul><a href="?public=contact">Discuss your robotics workflow →</a></article>
      <article class="mk-industry" id="medical"><div class="mk-kicker">Medical devices</div><h3>Support controlled design decisions with clearer evidence.</h3><p>Bring component lifecycle, supplier, and alternate-part evidence into engineering reviews where traceability and disciplined validation matter.</p><ul><li>Identify redesign pressure earlier</li><li>Document alternate-part decisions</li><li>Export review-ready summaries</li></ul><a href="?public=contact">Discuss your medical-device workflow →</a></article>
      <article class="mk-industry" id="industrial"><div class="mk-kicker">Industrial automation</div><h3>Maintain production continuity across long product lifecycles.</h3><p>Industrial controls and automation products often remain in service for years. Cadivor helps teams find component exposure before it reaches manufacturing or service operations.</p><ul><li>Review PLC, I/O, drive, and controller BOMs</li><li>Reduce single-source dependencies</li><li>Monitor components across installed platforms</li></ul><a href="?public=contact">Discuss your automation workflow →</a></article>
      <article class="mk-industry" id="aerospace"><div class="mk-kicker">Aerospace and defense</div><h3>Improve visibility into constrained and long-life electronics.</h3><p>Use structured engineering intelligence to support obsolescence review, supplier exposure analysis, and alternate qualification planning.</p><ul><li>Prioritize high-consequence component exposure</li><li>Maintain decision rationale</li><li>Support cross-functional review</li></ul><a href="?public=contact">Discuss your program needs →</a></article>
      <article class="mk-industry"><div class="mk-kicker">Consumer electronics</div><h3>Find sourcing and lifecycle risks before scale exposes them.</h3><p>Review product BOMs before volume manufacturing, where constrained components and late redesigns can quickly become expensive.</p><ul><li>Compare sourcing options before ramp</li><li>Identify inventory and concentration risk</li><li>Prepare alternate paths early</li></ul><a href="?public=contact">Discuss your product workflow →</a></article>
      <article class="mk-industry" id="startups"><div class="mk-kicker">Hardware startups</div><h3>Build a professional component-review process earlier.</h3><p>Give a small team the structure of a larger engineering organization without maintaining a collection of spreadsheets and supplier tabs.</p><ul><li>Review prototype and production BOMs</li><li>Communicate risk to investors and partners</li><li>Reduce expensive late-stage redesign</li></ul><a href="?auth=signup">Start your free trial →</a></article>
      <article class="mk-industry"><div class="mk-kicker">Universities and research</div><h3>Teach and apply disciplined BOM review.</h3><p>Help students and research teams understand lifecycle, sourcing, and engineering decision tradeoffs using real component data.</p><ul><li>Student plan for academic projects</li><li>Structured engineering review workflow</li><li>Exportable reports for project documentation</li></ul><a href="?auth=signup">Create a student workspace →</a></article>
      <article class="mk-industry"><div class="mk-kicker">Engineering consultancies</div><h3>Deliver consistent component-risk reviews across clients.</h3><p>Standardize BOM analysis, alternatives, evidence, and reporting across projects while maintaining clear decision history.</p><ul><li>Repeatable review methodology</li><li>Client-ready engineering reports</li><li>Portfolio visibility across engagements</li></ul><a href="?public=contact">Discuss a consultancy workflow →</a></article>
    </div></div></section>
    """)
    _cta("See how Cadivor fits your engineering workflow.", "Book a focused product walkthrough using a representative BOM.")
    _footer()


def _pricing() -> None:
    _page_hero("pricing", "Transparent pricing", "Start with full access. Scale when the workflow proves its value.", "Every new workspace receives a 14-day full-access trial before falling back to Starter. Student access is available for verified academic use.")
    _html("""
    <section class="mk-section"><div class="mk-wrap"><div class="mk-pricing">
      <div class="mk-price-card"><div class="mk-price-name">Student</div><div class="mk-price">$0</div><p>For verified students and academic engineering projects.</p><ul><li>10 BOM analyses per month</li><li>Up to 100 components per BOM</li><li>20 Ask Cadivor credits</li><li>Student-watermarked PDF reports</li></ul><a class="mk-btn mk-btn-light" href="?auth=signup" target="_self">Create Student Account</a></div>
      <div class="mk-price-card"><div class="mk-price-name">Starter</div><div class="mk-price">$29<small>/month</small></div><p>For individual prototype and early production reviews.</p><ul><li>10 BOM analyses per month</li><li>Up to 100 components per BOM</li><li>100 saved BOMs</li><li>30 Ask Cadivor credits</li></ul><a class="mk-btn mk-btn-light" href="?auth=signup" target="_self">Start Free Trial</a></div>
      <div class="mk-price-card featured"><div class="mk-popular">Most popular</div><div class="mk-price-name">Professional</div><div class="mk-price">$99<small>/month</small></div><p>For professional engineers and growing hardware teams.</p><ul><li>Unlimited BOM analyses</li><li>Unlimited components per BOM</li><li>2,500 monitored parts</li><li>500 Ask Cadivor credits</li></ul><a class="mk-btn mk-btn-primary" href="?auth=signup" target="_self">Start Free Trial</a></div>
      <div class="mk-price-card"><div class="mk-price-name">Business</div><div class="mk-price">$299<small>/month</small></div><p>For teams standardizing engineering decisions.</p><ul><li>Unlimited BOMs and monitoring</li><li>Team collaboration features</li><li>API access</li><li>2,500 Ask Cadivor credits</li></ul><a class="mk-btn mk-btn-light" href="?auth=signup" target="_self">Start Free Trial</a></div>
    </div></div></section>
    <section class="mk-section soft"><div class="mk-wrap"><div class="mk-heading"><div class="mk-kicker">Enterprise</div><h2>Secure, integrated, organization-wide deployment.</h2><p>Enterprise supports broader usage, custom workflows, priority engagement, and commercial terms aligned to your organization.</p></div><div class="mk-cta"><div><h2>Enterprise</h2><p>10,000 Ask Cadivor credits, unlimited platform entitlements, team features, API access, and organization-wide deployment support.</p></div><a class="mk-btn mk-btn-primary" href="?public=contact" target="_self">Contact Sales</a></div></div></section>
    <section class="mk-section"><div class="mk-wrap"><div class="mk-heading"><div class="mk-kicker">Plan comparison</div><h2>Choose the level that matches your review process.</h2></div><table class="mk-compare"><thead><tr><th>Capability</th><th>Student</th><th>Starter</th><th>Professional</th><th>Business</th><th>Enterprise</th></tr></thead><tbody><tr><td>BOM analyses</td><td>10/month</td><td>10/month</td><td class="mk-yes">Unlimited</td><td class="mk-yes">Unlimited</td><td class="mk-yes">Unlimited</td></tr><tr><td>Components per BOM</td><td>100</td><td>100</td><td class="mk-yes">Unlimited</td><td class="mk-yes">Unlimited</td><td class="mk-yes">Unlimited</td></tr><tr><td>Monitoring</td><td>—</td><td>—</td><td>2,500 parts</td><td class="mk-yes">Unlimited</td><td class="mk-yes">Unlimited</td></tr><tr><td>Team features</td><td>—</td><td>—</td><td>—</td><td class="mk-yes">Included</td><td class="mk-yes">Included</td></tr><tr><td>API access</td><td>—</td><td>—</td><td>—</td><td class="mk-yes">Included</td><td class="mk-yes">Included</td></tr><tr><td>PDF reports</td><td class="mk-partial">Student watermark</td><td class="mk-yes">Included</td><td class="mk-yes">Included</td><td class="mk-yes">Included</td><td class="mk-yes">Included</td></tr></tbody></table></div></section>
    <section class="mk-section soft"><div class="mk-wrap"><div class="mk-heading"><div class="mk-kicker">Pricing FAQ</div><h2>Questions before you begin</h2></div><div class="mk-faq"><div class="mk-faq-item"><strong>What happens after the 14-day trial?</strong><p>Your workspace falls back to Starter unless you choose a paid plan. Your saved data remains connected to your account.</p></div><div class="mk-faq-item"><strong>Is a credit card required for the trial?</strong><p>No. You can evaluate the full Cadivor workflow before selecting a plan.</p></div><div class="mk-faq-item"><strong>Who qualifies for Student?</strong><p>Student is intended for verified academic use and includes a watermark on generated PDF reports.</p></div><div class="mk-faq-item"><strong>Can Business users collaborate?</strong><p>Yes. Business and Enterprise include team capabilities and API access.</p></div></div></div></section>
    """)
    _footer()


def _resources() -> None:
    _page_hero("resources", "Engineering resources", "Build a stronger BOM review practice.", "Use Cadivor guides, demo BOMs, templates, and technical explanations to standardize how your team reviews component risk and engineering decisions.")
    _html("""
    <section class="mk-section soft"><div class="mk-wrap"><div class="mk-resource-grid">
      <article class="mk-resource"><div class="mk-resource-type">Getting started</div><h3>Your first Cadivor analysis</h3><p>Prepare a BOM, upload the file, understand the health score, review priority risks, and export a decision-ready report.</p><a href="?auth=signup">Open a workspace →</a></article>
      <article class="mk-resource"><div class="mk-resource-type">Template</div><h3>BOM formatting guide</h3><p>Use clear manufacturer part numbers and quantities. CSV and Excel files are supported.</p><a href="?auth=signup">Use a sample BOM →</a></article>
      <article class="mk-resource"><div class="mk-resource-type">Engineering guide</div><h3>How to evaluate lifecycle exposure</h3><p>Understand Active, NRND, EOL, obsolete, and unknown lifecycle signals—and how each should affect a release decision.</p><a href="?public=contact">Request the guide →</a></article>
      <article class="mk-resource"><div class="mk-resource-type">Engineering guide</div><h3>Single-source risk review</h3><p>Learn when supplier concentration becomes an engineering concern and what evidence supports alternate qualification.</p><a href="?public=contact">Request the guide →</a></article>
      <article class="mk-resource"><div class="mk-resource-type">Demo BOM</div><h3>Industrial controller example</h3><p>Explore a representative analysis with lifecycle issues, sourcing concentration, alternatives, and release recommendations.</p><a href="?auth=signup">Analyze a demo BOM →</a></article>
      <article class="mk-resource"><div class="mk-resource-type">Release notes</div><h3>Cadivor launch edition</h3><p>Engineering Intelligence, Ask Cadivor, Executive Decision Cockpit, navigation continuity, reports, and portfolio workflows.</p><a href="?public=product">Review the platform →</a></article>
    </div></div></section>
    <section class="mk-section"><div class="mk-wrap"><div class="mk-heading"><div class="mk-kicker">Frequently asked questions</div><h2>What engineering teams ask before using Cadivor</h2></div><div class="mk-faq"><div class="mk-faq-item"><strong>What file formats are supported?</strong><p>Cadivor accepts CSV and Excel files. A clean manufacturer part-number column and quantity column produce the best results.</p></div><div class="mk-faq-item"><strong>Which supplier integrations are active?</strong><p>Cadivor currently integrates supplier intelligence from DigiKey, Mouser, and Newark. Coverage can vary by component and source availability.</p></div><div class="mk-faq-item"><strong>Does Cadivor replace engineering validation?</strong><p>No. Cadivor supports decisions. Teams remain responsible for datasheet review, compatibility verification, supplier confirmation, qualification testing, and production approval.</p></div><div class="mk-faq-item"><strong>How are alternatives evaluated?</strong><p>Cadivor considers available lifecycle, supplier, inventory, sourcing, and engineering-compatibility evidence. Every candidate must still be validated for the specific design.</p></div><div class="mk-faq-item"><strong>Can I ask questions about a BOM?</strong><p>Yes. Ask Cadivor supports contextual questions about the active analysis, risk priorities, production readiness, suppliers, alternatives, and recommendation evidence.</p></div><div class="mk-faq-item"><strong>Can reports be exported?</strong><p>Yes. Cadivor provides exportable executive, lifecycle, and engineering review reports according to plan entitlements.</p></div></div></div></section>
    """)
    _cta("Start with a real BOM and see what Cadivor surfaces.", "Create a workspace and run your first analysis in minutes.")
    _footer()


def _company() -> None:
    _page_hero("company", "About Cadivor", "Hardware teams deserve better decision infrastructure.", "Cadivor was created to replace fragmented BOM review with a connected engineering intelligence workflow built around evidence, priorities, and action.")
    _html("""
    <section class="mk-section"><div class="mk-wrap mk-feature-split"><div class="mk-feature-copy"><div class="mk-kicker">Mission</div><h2>Help engineering teams make better decisions before problems reach production.</h2><p>Component information is abundant, but engineering teams still spend hours connecting supplier pages, spreadsheets, lifecycle signals, alternatives, and review notes. Cadivor turns that fragmented process into a repeatable engineering workflow.</p></div><div class="mk-surface"><div class="mk-card" style="box-shadow:none"><div class="mk-icon">C</div><h3>Our core promise</h3><p>Upload a BOM. Understand the risks. See what matters. Decide what to do next.</p></div></div></div></section>
    <section class="mk-section soft"><div class="mk-wrap"><div class="mk-heading"><div class="mk-kicker">Operating principles</div><h2>Engineering-first by design</h2></div><div class="mk-card-grid"><div class="mk-card"><div class="mk-icon">1</div><h3>Evidence over hype</h3><p>Recommendations should be connected to visible component, supplier, lifecycle, and workflow evidence.</p></div><div class="mk-card"><div class="mk-icon">2</div><h3>Decisions over dashboards</h3><p>Metrics matter only when they help a team understand what to review, qualify, or approve next.</p></div><div class="mk-card"><div class="mk-icon">3</div><h3>Human accountability</h3><p>Cadivor supports engineering judgment; it does not replace professional validation or production authority.</p></div></div></div></section>
    <section class="mk-section"><div class="mk-wrap"><div class="mk-heading"><div class="mk-kicker">Vision</div><h2>The engineering intelligence layer for hardware organizations.</h2><p>Cadivor's long-term direction connects BOM risk, design decisions, alternatives, monitoring, supplier evidence, collaboration, and product-lifecycle intelligence in one trusted platform.</p></div></div></section>
    """)
    _cta("Help shape the future of engineering intelligence.", "Join the launch program, evaluate Cadivor on a real BOM, and share direct product feedback.")
    _footer()


def _contact() -> None:
    _page_hero("company", "Contact Cadivor", "Start a practical conversation about your BOM review workflow.", "Use the contact options below for product demos, beta participation, commercial questions, support, or partnership discussions.")
    _html("""
    <section class="mk-section soft"><div class="mk-wrap"><div class="mk-card-grid"><div class="mk-card"><div class="mk-icon">▶</div><h3>Book a product demo</h3><p>Walk through BOM analysis, Engineering Intelligence, Ask Cadivor, alternatives, monitoring, and reports using a representative workflow.</p><a href="mailto:info@cadivor.com?subject=Cadivor%20Demo%20Request">info@cadivor.com →</a></div><div class="mk-card"><div class="mk-icon">β</div><h3>Join the beta program</h3><p>Evaluate Cadivor with a real engineering team and provide feedback that directly influences launch priorities.</p><a href="mailto:info@cadivor.com?subject=Cadivor%20Beta%20Program">Request beta access →</a></div><div class="mk-card"><div class="mk-icon">?</div><h3>Product and support</h3><p>Ask a question about accounts, BOM formatting, plan entitlements, reports, or the engineering workflow.</p><a href="mailto:info@cadivor.com?subject=Cadivor%20Product%20Question">Contact support →</a></div></div></div></section>
    <section class="mk-section"><div class="mk-wrap"><div class="mk-heading"><div class="mk-kicker">Prepare for a productive demo</div><h2>Bring one representative workflow.</h2><p>A useful conversation starts with the type of BOM you review, the risks you currently track, the teams involved in release decisions, and the output you need at the end.</p></div><div class="mk-steps"><div class="mk-step"><div class="mk-step-num">1</div><h3>Choose a BOM</h3><p>Select a representative prototype, production, redesign, or sustaining-engineering BOM.</p></div><div class="mk-step"><div class="mk-step-num">2</div><h3>Identify the decision</h3><p>Define what the team needs to approve, qualify, replace, or monitor.</p></div><div class="mk-step"><div class="mk-step-num">3</div><h3>Map the workflow</h3><p>Note who reviews component, supplier, procurement, and production evidence.</p></div><div class="mk-step"><div class="mk-step-num">4</div><h3>Evaluate the result</h3><p>Compare Cadivor's output with your existing review process.</p></div></div></div></section>
    """)
    _footer()


def _legal_page(kind: str) -> None:
    titles = {
        "security": ("Security", "Responsible handling of engineering data.", "Cadivor uses managed authentication, access controls, and cloud infrastructure to support secure workspace operation."),
        "privacy": ("Privacy Policy", "How Cadivor handles account and product data.", "This pre-launch policy describes the information Cadivor processes to provide, secure, support, and improve the service."),
        "terms": ("Terms of Service", "The conditions for using Cadivor.", "Cadivor is an engineering decision-support platform. Final production, procurement, qualification, and regulatory decisions remain with the customer."),
    }
    title, heading, copy = titles[kind]
    _page_hero("company", title, heading, copy)
    if kind == "security":
        body = """
        <section class="mk-section"><div class="mk-wrap"><div class="mk-card-grid"><div class="mk-card"><div class="mk-icon">🔒</div><h3>Authentication</h3><p>Cadivor uses managed authentication and session controls to protect access to customer workspaces.</p></div><div class="mk-card"><div class="mk-icon">◆</div><h3>Workspace separation</h3><p>Application data is associated with authenticated user and organization contexts, supported by database access policies.</p></div><div class="mk-card"><div class="mk-icon">↻</div><h3>Responsible operations</h3><p>Security, reliability, backup, access review, and incident-response practices will continue to mature through commercial launch.</p></div></div><div class="mk-faq" style="margin-top:28px"><div class="mk-faq-item"><strong>Customer responsibility</strong><p>Do not upload information you are not authorized to process. Export-controlled, regulated, or highly sensitive data requires an appropriate contractual and security review before use.</p></div><div class="mk-faq-item"><strong>Security inquiries</strong><p>Send security and responsible-disclosure questions to info@cadivor.com with “Security” in the subject line.</p></div></div></div></section>"""
    elif kind == "privacy":
        body = """
        <section class="mk-section"><div class="mk-wrap"><div class="mk-feature-copy"><h2>Pre-launch privacy notice</h2><p>Cadivor may process account information, authentication data, uploaded BOM content, analysis results, reports, usage records, support communications, billing status, and technical logs necessary to operate the service.</p><div class="mk-check-list"><div class="mk-check"><b>1</b><span><strong>Purpose:</strong> provide analysis, save workspace state, generate reports, enforce plan limits, process subscriptions, support users, prevent abuse, and improve reliability.</span></div><div class="mk-check"><b>2</b><span><strong>Service providers:</strong> Cadivor may rely on cloud hosting, authentication, database, payment, supplier-data, and AI service providers to perform product functions.</span></div><div class="mk-check"><b>3</b><span><strong>Customer control:</strong> customers remain responsible for ensuring they have authority to upload and process their BOM data.</span></div><div class="mk-check"><b>4</b><span><strong>Contact:</strong> privacy questions may be sent to info@cadivor.com.</span></div></div><p style="margin-top:28px"><em>This draft must receive qualified legal review and be updated with the final legal entity, address, retention terms, jurisdictional disclosures, subprocessors, and data-rights procedure before commercial launch.</em></p></div></div></section>"""
    else:
        body = """
        <section class="mk-section"><div class="mk-wrap"><div class="mk-feature-copy"><h2>Pre-launch terms summary</h2><p>By creating an account or using Cadivor, you agree that Cadivor provides software-based component lifecycle, sourcing, supplier, risk, alternative-part, reporting, and AI-assisted engineering intelligence for informational and decision-support purposes.</p><div class="mk-check-list"><div class="mk-check"><b>1</b><span>Cadivor does not replace professional engineering judgment, datasheet review, supplier confirmation, regulatory review, qualification testing, procurement approval, manufacturing review, or production release authority.</span></div><div class="mk-check"><b>2</b><span>You remain responsible for validating every component, alternate, compatibility claim, lifecycle status, supplier listing, stock level, lead time, risk score, and manufacturing decision.</span></div><div class="mk-check"><b>3</b><span>You must have the legal authority to upload and process all data submitted to the service.</span></div><div class="mk-check"><b>4</b><span>Supplier records, public sources, software rules, and AI-assisted outputs may be incomplete, delayed, inaccurate, or unsuitable for a particular design.</span></div></div><p style="margin-top:28px"><em>This draft must receive qualified legal review and be updated with the final legal entity, billing terms, governing law, warranty language, liability limitations, support contact, and dispute procedure before commercial launch.</em></p></div></div></section>"""
    _html(body)
    _footer()


def render_marketing_site() -> None:
    """Render the signed-out Sprint 51 marketing website."""
    _marketing_css()
    try:
        raw = st.query_params.get("public", "home")
        page = raw[0] if isinstance(raw, list) else raw
    except Exception:
        page = "home"
    routes = {
        "home": _home,
        "product": _product,
        "features": _product,
        "solutions": _solutions,
        "pricing": _pricing,
        "resources": _resources,
        "company": _company,
        "contact": _contact,
        "security": lambda: _legal_page("security"),
        "privacy": lambda: _legal_page("privacy"),
        "terms": lambda: _legal_page("terms"),
    }
    routes.get(str(page or "home").lower(), _home)()
